---
name: Data submission form (exposure-vulnerability data)
description: Suggest a new exposure or vulnerability dataset to be included in the living catalog
labels: [Expvul, Enhancement]

body:
  - type: checkboxes
    attributes:
      label: Duplicate check
      options:
        - label: >
            I have checked that the dataset is not yet included in the catalog.
          required: true

  - type: dropdown
    id: catalog
    attributes:
      description: Overarching catalog that the data belong to (i.e. hazard, exposure-vulnerability)
      label: Catalog
      options:
        - exposure-vulnerability
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      description: Category of data type according to classification scheme (see classification in README, grey boxes)
      label: Category
      options:
        - population
        - buildings
        - infrastructure
        - land use
    validations:
      required: true

  - type: dropdown
    id: subcategory
    attributes:
      description: Subcategory of data type according to classification scheme (see classification in README, light blue and yellow boxes)
      label: Subcategory
      options:
        - population number
        - demographics
        - socioeconomic status
        - adaptive capacity
        - vulnerability index
        - building footprints
        - building characteristics
        - infrastructure footprints
        - infrastructure characteristics
        - urban/built-up footprints
        - land use/land cover footprints
        - urban/built-up characteristics
        - land use/land cover characteristics
        - not specified
    validations:
      required: true

  - type: dropdown
    id: risk-data-type
    attributes:
      description: Risk driver (i.e. hazard, exposure, vulnerability, response)
      label: Risk data type
      options:
        - exposure
        - vulnerability
        - response
    validations:
      required: true

  - type: input
    id: title-collection
    attributes:
      description: Name of the dataset collection; the collection title must be the same for each item belonging to that collection (see 'Item title' for further instructions).
      label: Collection title
      placeholder: ex. Critical Infrastructure Spatial Index
    validations:
      required: true

  - type: input
    id: title-short
    attributes:
      description: Short name/acronym of the dataset (if available)
      label: Title short
      placeholder: ex. CISI

  - type: textarea
    id: description-collection
    attributes:
      description: Detailed description of the dataset collection; the collection description must be the same for each item belonging to that collection
      label: Collection description
      placeholder: ex. The Critical Infrastructure Spatial Index (CISI) is calculated from 39 critical infrastructure types (e.g. airports, clinics, landfills, reservoirs, schools) downloaded from Open Street Map (OSM).
    validations:
      required: true

  - type: input
    id: title-item
    attributes:
      description: Concise name of the dataset item; each item from the same collection needs to have a unique name. If data are from the same overall data source, but metadata attributes differ, these are separate items that belong to the same collection. Please submit separate data items per collection by creating a new issue.
      label: Item title
      placeholder: ex. Index 0.1 dec deg
    validations:
      required: true

  - type: textarea
    id: description-item
    attributes:
      description: Detailed description of the dataset item; if there is only one item in the collection, the collection description can be copied here.
      label: Item description
      placeholder: ex. CISI at a spatial resolution of 0.1 decimal degrees
    validations:
      required: true

  - type: dropdown
    id: spatial-scale
    attributes:
      label: Spatial scale
      description: Spatial coverage of the dataset
      options:
        - (near-)global
        - regional
        - national
        - subnational
    validations:
      required: true

  - type: input
    id: bbox
    attributes:
      description: Bounding box (i.e. spatial extent) of the dataset given in WGS84 coordinates (xmin, ymin, xmax, ymax)
      label: Bounding box
      placeholder: ex. -180, -90, 180, 90
    validations:
      required: true

  - type: dropdown
    id: reference-period
    attributes:
      label: Reference period
      description: Reference period for which the data are available 
      options:
        - historical
        - future
        - historical & future
    validations:
      required: true

  - type: input
    id: temporal-coverage
    attributes:
      description: Temporal coverage of the data in years (i.e. YYYY for one time step; YYYY-YYYY for time series; YYYY-now if data are updated in real time)
      label: Temporal coverage
      placeholder: ex. 2021
    validations:
      required: true

  - type: dropdown
    id: temporal-interval
    attributes:
      label: Temporal interval
      description: Time steps that the data are reported in (optional)
      options:
        - hourly
        - 3-hourly
        - daily
        - 10-days
        - monthly
        - yearly
        - 5-yearly
        - 6-yearly
        - 10-yearly
        - irregular
  
  - type: dropdown
    id: scenarios
    attributes:
      description: Name of the scenarios used if 'Reference period' is 'future'
      label: Scenarios
      options: 
        - SSPs
        - SSP-RCP combinations
        - warming levels
        - extrapolation
        - other (please specify below)

  - type: input
    id: custom-scenarios
    attributes:
      label: New scenarios
      description: If 'other' selected in 'Scenarios', please specify the name of the scenarios here
      placeholder: Enter name of scenarios

  - type: dropdown
    id: data-type
    attributes:
      label: Data type
      description: Geospatial data type of the dataset (if more than one available, please submit a new item)
      options:
        - raster
        - vector
        - tabular
    validations:
      required: true

  - type: dropdown
    id: data-format
    attributes:
      label: Data format
      description: Geospatial data format of the dataset (if more than one available, please submit a new item)
      options:
        - geotiff
        - netcdf
        - geopackage
        - shapefile
        - geodatabase
        - FlatGeobuf
        - GeoParquet
        - GRIB
        - GRIB2
        - csv
        - excel
        - ascii
        - txt
        - pbf
        - other (please specify below)
    validations:
      required: true

  - type: input
    id: custom-data-format
    attributes:
      label: New data format
      description: If 'other' selected in 'Data format', please specify the data format here
      placeholder: Enter new data format

  - type: input
    id: spatial-resolution
    attributes:
      label: Spatial resolution
      description: Spatial resolution in numeric value or as a string, e.g. "administrative unit", "feature level", "event" (if more than one available, please submit a new item)
      placeholder: ex. 0.1
    validations:
      required: true

  - type: dropdown
    id: spatial-resolution-unit
    attributes:
      label: Spatial resolution unit
      description: If 'Spatial resolution' numeric or "administrative unit", please specify the spatial resolution unit here
      options:
        - arc seconds
        - arc minutes
        - decimal degrees
        - meters
        - kilometers
        - admin1
        - admin2
        - admin3

  - type: input
    id: coordinate-reference-system
    attributes:
      label: Coordinate reference system
      description: Numerical code (e.g. EPSG, ESRI code) of the coordinate reference system (CRS) (e.g. 4326, 54009) (if more than one available, please submit a new item)
      placeholder: ex. 4326
    validations:
      required: true
  
  - type: dropdown
    id: source-type
    attributes:
      label: Source type
      description: Indicates whether the data is directly observed from real-world measurements or generated through modeling or simulations (i.e. observed, modeled)
      options:
        - observed
        - modeled
    validations:
      required: true

  - type: input
    id: analysis-type
    attributes:
      label: Analysis type
      description: Method used to generate the data (optional)
      placeholder: ex. equal weighting

  - type: input
    id: underlying-data
    attributes:
      label: Underlying data
      description: Data underlying the calculation and analysis type (optional)
      placeholder: ex. Open Street Map (OSM)

  - type: input
    id: provider-name
    attributes:
      label: Provider name
      description: Name of data provider
      placeholder: ex. Zenodo
    validations:
      required: true

  - type: dropdown
    id: provider-role
    attributes:
      label: Provider role
      description: Role of data provider
      options:
        - licensor
        - producer
        - processor
        - host
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: License
      description: Data distribution license
      options:
        - CC0-1.0
        - CC-BY-4.0
        - CC-BY-SA-4.0
        - CC-BY-NC-SA-4.0
        - CC BY-ND 4.0
        - CC BY-NC-ND 4.0
        - ODbL-1.0
        - ODC-By-1.0
        - PDDL-1.0
        - GNU General Public License
        - CC-BY-3.0 IGO
        - CDLA-Permissive-1.0
        - proprietary
        - other (please specify below)
    validations:
      required: true

  - type: input
    id: custom-license
    attributes:
      label: New license
      description: If 'other' selected in 'License', please specify the license here (open-access licenses only)
      placeholder: Enter new data license

  - type: input
    id: data-overview-link
    attributes:
      label: Data overview link
      description: URL to website where the dataset is described and can be accessed
      placeholder: ex. https://zenodo.org/records/4957647
    validations:
      required: true

  - type: input
    id: publication-link
    attributes:
      label: Publication link
      description: Link to publication; DOI if available, starting with '10.' (optional)
      placeholder: ex. 10.1038/s41597-022-01218-4

  - type: dropdown
    id: publication-type
    attributes:
      label: Publication type
      description: Type of publication (if 'Publication link' provided)
      options:
        - article
        - report
        - documentation
        - dataset

  - type: input
    id: code-link
    attributes:
      label: Code link
      description: Link to available code; DOI if available, starting with '10.' (optional)
      placeholder: ex. 10.5281/zenodo.4819988

  - type: dropdown
    id: code-type
    attributes:
      label: Code type
      description: Type of available code (if 'Code link' provided)
      options:
        - download
        - processing
        - application
        - visualization

  - type: textarea
    id: usage-notes
    attributes:
      label: Usage notes
      description: Any relevant information for using the data
      placeholder: ex. The CISI is developed from OSM data and its spatial coverage depends on the completeness of OSM records.

  - type: input
    id: asset-links
    attributes:
      label: Asset links
      description: URL to specific data files or download page (separated with ' ')
      placeholder: ex. https://zenodo.org/records/4957647/files/CISI.zip?download=1
    validations:
      required: true

  - type: textarea
    id: further-details
    attributes:
      description: Please provide any further details relevant for this new data entry
      label: Further details
      placeholder: Add any relevant information not provided before, problems encountered while filling in the form etc.
