---
title: "How to browse"
---

Browse STAC via STAC Browser: add brief introduction


### Catalogs

-   underlying folder structure of the living catalog
    -   first level:
    -   second level:
-   can be filtered by title, descriptions and keywords

::: {.callout-warning}
Collections are listed as "Catalogs" in STAC Browser.
::: 

### Collections
-   Their functionality is similar to catalogs, but their contain important overall data source information
-   keywords can be selected for filtering
-   contain important metadata (link to metadata overview table here?) that all data entries (= items) have in common
    -   description
    -   keywords
    -   license
    -   overall temporal extent
    -   overall spatial footprint
    -   data provider including weblink
-   links to corresponding items

::: {.callout-important}
Very important: at least one item per collection
::: 

### Items 
-   vast majority of metadata attributes (link to metadata overview table here)
    -   technical specifications of the data entry
    -   additional information relevant for CRAs
    -   additional resources such as links to publications and code (if available)
    -   assets = define here



